---
title: "R Notebook"
output:
  pdf_document: default
  html_document:
    df_print: paged
---
```{r "setup", include=FALSE}
knitr::opts_knit$set(root.dir = normalizePath('C:\\Users\\maxim\\Dropbox (EinsteinMed)\\CloudStation\\PRMT\\polyA enrichment/'))
library(tidyverse)
library(ggrepel)
```

```{r}

#['#b2182b','#ef8a62','#fddbc7','#f7f7f7','#d1e5f0','#67a9cf','#2166ac']

data <- read.csv('InputChromatin_GSK_vs_DMSO.csv')
data$Score <- abs(data$Score)
data <- data[order(data$p.value, decreasing = TRUE),]

#DMSO_color <- '#d4d4d4'
#GSK_color <- '#008837'
#MS023_color <- '#7b3294'

data$df <- 'group'
terms <- c('Transport of Mature', 'RNA transport', 'Spliceosome', 'mRNA splicing', 'mRNA surveillance', 'RNA degradation')
data$pathways <- paste(data$Molecular.Function, data$KEGG.Pathways, data$Reactome.Pathways, sep = ';')

data$transport <- ifelse(grepl(paste(terms,collapse='|'), data$pathways, ignore.case = TRUE), "yes", "no")

data <- data[order(data$transport),]
ggplot(data, aes(x=df, y=GSK.DMSO, color = group, label = Gene.Symbol)) +
  geom_jitter(aes(size=p.value, alpha = group, colour = transport),width=0.1, height=0.1, shape = 20, alpha = 0.5) +
  scale_color_manual(values= c('#d4d4d4','#008837')) +
  geom_text_repel(data = subset(data, transport == 'yes')[1:15,], aes(label=Gene.Symbol),  size=2, colour = "black", max.overlaps = 100)+
  theme(legend.position = "none",
        axis.text.y   = element_text(size=8, colour = "black"),
        axis.text.x   = element_text(size=8, colour = "black"),
        axis.title.y  = element_text(size=8, colour = "black"),
        axis.title.x  = element_text(size=8, colour = "black"),
        panel.background = element_blank(),
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.line = element_line(colour = "black"),
        panel.border = element_rect(colour = "black", fill=NA, size=1))+
  #geom_vline(xintercept=c(0), linetype="solid")+
  geom_hline(yintercept=c(0), linetype="solid")+
  #geom_hline(yintercept=c(4.4), linetype="dotted")+
  ylim(-7,7)+
  #scale_y_continuous(limits = c(0,20), expand = c(0, 0)) +
  labs(title="",x="", y = "log2FC")

```
```{r}

#['#b2182b','#ef8a62','#fddbc7','#f7f7f7','#d1e5f0','#67a9cf','#2166ac']
data <- read.csv('polyA_backgroundsubtracted_GSK_vs_DMSO.csv')
data$Score <- abs(data$Score)
data <- data[order(data$p.value, decreasing = TRUE),]

#DMSO_color <- '#d4d4d4'
#GSK_color <- '#008837'
#MS023_color <- '#7b3294'

data$df <- 'group'
terms <- c('Transport of Mature', 'RNA transport', 'Spliceosome', 'mRNA splicing', 'mRNA surveillance', 'RNA degradation')
data$pathways <- paste(data$Molecular.Function, data$KEGG.Pathways, data$Reactome.Pathways, sep = ';')

data$transport <- ifelse(grepl(paste(terms,collapse='|'), data$pathways, ignore.case = TRUE), "yes", "no")

data <- data[order(data$transport),]
ggplot(data, aes(x=df, y=GSK.DMSO, color = group, label = Gene.Symbol)) +
  geom_jitter(aes(size=p.value, alpha = group, colour = transport),width=0.1, height=0.1, shape = 20, alpha = 0.5) +
  scale_color_manual(values= c('#d4d4d4','#008837')) +
  geom_text_repel(data = subset(data, transport == 'yes')[1:15,], aes(label=Gene.Symbol),  size=2, colour = "black", max.overlaps = 100)+
  theme(legend.position = "none",
        axis.text.y   = element_text(size=8, colour = "black"),
        axis.text.x   = element_text(size=8, colour = "black"),
        axis.title.y  = element_text(size=8, colour = "black"),
        axis.title.x  = element_text(size=8, colour = "black"),
        panel.background = element_blank(),
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.line = element_line(colour = "black"),
        panel.border = element_rect(colour = "black", fill=NA, size=1))+
  #geom_vline(xintercept=c(0), linetype="solid")+
  geom_hline(yintercept=c(0), linetype="solid")+
  #geom_hline(yintercept=c(4.4), linetype="dotted")+
  ylim(-10,10)+
  #scale_y_continuous(limits = c(0,20), expand = c(0, 0)) +
  labs(title="",x="", y = "log2FC")

```


```{r}

#['#b2182b','#ef8a62','#fddbc7','#f7f7f7','#d1e5f0','#67a9cf','#2166ac']

data <- read.csv('InputChromatin_MS023_vs_DMSO.csv')
data$Score <- abs(data$Score)
data <- data[order(data$p.value, decreasing = TRUE),]

#DMSO_color <- '#d4d4d4'
#GSK_color <- '#008837'
#MS023_color <- '#7b3294'

data$df <- 'group'
terms <- c('Transport of Mature', 'RNA transport', 'Spliceosome', 'mRNA splicing', 'mRNA surveillance', 'RNA degradation')
data$pathways <- paste(data$Molecular.Function, data$KEGG.Pathways, data$Reactome.Pathways, sep = ';')

data$transport <- ifelse(grepl(paste(terms,collapse='|'), data$pathways, ignore.case = TRUE), "yes", "no")

data <- data[order(data$transport),]
ggplot(data, aes(x=df, y=MS023.DMSO, color = group, label = Gene.Symbol)) +
  geom_jitter(aes(size=p.value, alpha = group, colour = transport),width=0.1, height=0.1, shape = 20, alpha = 0.5) +
  scale_color_manual(values= c('#d4d4d4','#7b3294')) +
  geom_text_repel(data = subset(data, transport == 'yes')[1:15,], aes(label=Gene.Symbol),  size=2, colour = "black", max.overlaps = 100)+
  theme(legend.position = "none",
        axis.text.y   = element_text(size=8, colour = "black"),
        axis.text.x   = element_text(size=8, colour = "black"),
        axis.title.y  = element_text(size=8, colour = "black"),
        axis.title.x  = element_text(size=8, colour = "black"),
        panel.background = element_blank(),
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.line = element_line(colour = "black"),
        panel.border = element_rect(colour = "black", fill=NA, size=1))+
  #geom_vline(xintercept=c(0), linetype="solid")+
  geom_hline(yintercept=c(0), linetype="solid")+
  #geom_hline(yintercept=c(4.4), linetype="dotted")+
  ylim(-7,7)+
  #scale_y_continuous(limits = c(0,20), expand = c(0, 0)) +
  labs(title="",x="", y = "log2FC")

```

```{r}

#['#b2182b','#ef8a62','#fddbc7','#f7f7f7','#d1e5f0','#67a9cf','#2166ac']

data <- read.csv('polyA_backgroundsubtracted_MS023_vs_DMSO.csv')
data$Score <- abs(data$Score)
data <- data[order(data$p.value, decreasing = TRUE),]

#DMSO_color <- '#d4d4d4'
#GSK_color <- '#008837'
#MS023_color <- '#7b3294'

data$df <- 'group'
terms <- c('Transport of Mature', 'RNA transport', 'Spliceosome', 'mRNA splicing', 'mRNA surveillance', 'RNA degradation')
data$pathways <- paste(data$Molecular.Function, data$KEGG.Pathways, data$Reactome.Pathways, sep = ';')


data$transport <- ifelse(grepl(paste(terms,collapse='|'), data$pathways, ignore.case = TRUE), "yes", "no")

data <- data[order(data$transport),]
ggplot(data, aes(x=df, y=MS023.DMSO, color = group, label = Gene.Symbol)) +
  geom_jitter(aes(size=p.value, alpha = group, colour = transport),width=0.1, height=0.1, shape = 20, alpha = 0.5) +
  scale_color_manual(values= c('#d4d4d4','#7b3294')) +
  geom_text_repel(data = subset(data, transport == 'yes')[1:15,], aes(label=Gene.Symbol),  size=2, colour = "black", max.overlaps = 100)+
  theme(legend.position = "none",
        axis.text.y   = element_text(size=8, colour = "black"),
        axis.text.x   = element_text(size=8, colour = "black"),
        axis.title.y  = element_text(size=8, colour = "black"),
        axis.title.x  = element_text(size=8, colour = "black"),
        panel.background = element_blank(),
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.line = element_line(colour = "black"),
        panel.border = element_rect(colour = "black", fill=NA, size=1))+
  #geom_vline(xintercept=c(0), linetype="solid")+
  geom_hline(yintercept=c(0), linetype="solid")+
  #geom_hline(yintercept=c(4.4), linetype="dotted")+
  ylim(-10,10)+
  #scale_y_continuous(limits = c(0,20), expand = c(0, 0)) +
  labs(title="",x="", y = "log2FC")

```