---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---

```{r "setup", include=FALSE}
knitr::opts_knit$set(root.dir = normalizePath('C:\\Users\\maxim\\Dropbox (EinsteinMed)\\CloudStation\\PRMT\\'))
library(tidyverse)
library(reshape2)
```

```{r}
d2g <- read.table('SKaTER/Sequencing_Analysis/results/GSK591rep1_GSK591rep2_fractionCleavageBeforeSplicing.txt', header = T, sep = '\t')
d2m <- read.table('SKaTER/Sequencing_Analysis/results/MS023rep1_MS023rep2_fractionCleavageBeforeSplicing.txt', header = T, sep = '\t')
dmso <- read.table('SKaTER/Sequencing_Analysis/results/DMSOrep1_DMSOrep2_fractionCleavageBeforeSplicing.txt', header = T, sep = '\t')

#compile a list of dataframes
dataframes <- list(d2g = d2g, d2m = d2m, dmso = dmso)
dataframes <- dataframes %>% reduce(inner_join, by = 'intron')
colnames(dataframes)[6] <- 'd2g'
colnames(dataframes)[11] <- 'd2m'
colnames(dataframes)[16] <- 'dmso'
dataframes <- dataframes[c(1,6,11,16)]

df <- melt(dataframes)
#define colors for graph
colors <- c('#D4D4D4','#008837','#7b3294')
#define order of graph
order <- c( 'dmso','d2g', 'd2m')
#convert dataframe names to factors to allow ordering
df$variable <- factor(df$variable, levels = order)

stat_box_data <- function(y, upper_limit = max(df$value) * 1.15) {
  return( 
    data.frame(
      y = 0.95 * upper_limit,
      label = paste('count =', length(y), '\n',
                    'median =', round(median(y), 3), '\n')
    )
  )
}

```

```{r}
#pdf('R_figures/SKaTER_probability_cleavage_prior_to_splicing_violin_corrected.pdf', height = 10, width = 10)
ggplot(df, aes(x=variable, fill=variable, y=value))+
  scale_fill_manual(values=colors)+
  geom_violin(alpha=0.5, orientation = 'x', width=1, position=position_dodge(width=0.5))+
  #geom_jitter(aes(x=group, y=rate), shape =21)+
  geom_boxplot(width=0.1, fatten=5)+
  geom_hline(yintercept= median(df[df$variable == 'dmso',]$value),size=1, linetype ='dotted') +
  scale_color_manual(values=c('#afadae','#f2a182')) +
  theme(legend.position = "right", legend.key = element_rect(colour = NA, fill = NA)) +
  theme(panel.background = element_blank()) +
  theme(panel.grid.minor = element_blank()) +
  labs(title="", y = "Probability of Cleavage Prior to Splicing", x="")+
  stat_summary(
    fun.data = stat_box_data, 
    geom = "text", 
    hjust = 0.5,
    vjust = 0.9
  )
#dev.off()
```

```{r message=FALSE, warning = FALSE, include=FALSE}
ks.test(df[df$variable == 'dmso',]$value, df[df$variable == 'd2g',]$value)
ks.test(df[df$variable == 'dmso',]$value, df[df$variable == 'd2m',]$value)
ks.test(df[df$variable == 'd2m',]$value, df[df$variable == 'd2g',]$value)

wilcox.test(df[df$variable == 'dmso',]$value, df[df$variable == 'd2g',]$value)
wilcox.test(df[df$variable == 'dmso',]$value, df[df$variable == 'd2m',]$value)
wilcox.test(df[df$variable == 'd2m',]$value, df[df$variable == 'd2g',]$value)
```


